threshold: 95
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Zyra.register
      - Zyra.after
      - Zyra.build
      - Zyra.create
      - Zyra::Builder#after
      - Zyra::Builder#build
      - Zyra::Builder#create
      - Zyra::Registry#register
      - Zyra::Finder#after
  ReturnTag:
    enabled: true
    exclude:
      - Zyra.after
      - Zyra.build
      - Zyra.create
  Summary::Presence:
    enabled: true
    exclude:
      - Zyra::Builder#initialize
      - Zyra::Finder#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
